export const jobCategories = [
  "Software Development",
  "Data Science",
  "Product Management",
  "Marketing",
  "Sales",
  "Customer Support",
  "Finance",
  "Human Resources",
  "Graphic Design",
  "Content Writing",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Education and Training",
  "Healthcare",
  "Legal Services",
  "Logistics and Supply Chain",
  "Retail Management",
  "Hospitality",
  "Event Management",
  "Social Media Management",
  "IT Support",
  "Cybersecurity",
  "Cloud Computing",
  "AI and Machine Learning",
  "DevOps",
  "Mobile App Development",
  "Game Development",
  "Data Engineering",
  "Database Administration",
  "Quality Assurance",
  "Architecture",
  "Construction Management",
  "Public Relations",
  "Business Analysis",
  "Operations Management",
  "Procurement",
  "Digital Marketing",
  "Advertising",
  "Technical Writing",
  "Copywriting",
  "Environmental Science",
  "Biotechnology",
  "Pharmaceuticals",
  "Telecommunications",
  "Agriculture",
  "E-commerce",
  "Media and Entertainment",
  "Research and Development",
  "Real Estate",
  "Transportation",
];
export const jobDesignations = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Specialist",
  "Product Manager",
  "Project Manager",
  "Marketing Manager",
  "Sales Executive",
  "Business Development Manager",
  "HR Manager",
  "Recruiter",
  "UI/UX Designer",
  "Graphic Designer",
  "Content Writer",
  "Copywriter",
  "Digital Marketer",
  "SEO Specialist",
  "Social Media Manager",
  "DevOps Engineer",
  "Cloud Architect",
  "Cybersecurity Analyst",
  "Network Engineer",
  "Mobile App Developer",
  "Game Developer",
  "Database Administrator",
  "Data Engineer",
  "QA Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Architect",
  "Teacher",
  "Professor",
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Legal Advisor",
  "Lawyer",
  "Paralegal",
  "Accountant",
  "Financial Analyst",
  "Investment Banker",
  "Operations Manager",
  "Logistics Manager",
  "Supply Chain Specialist",
  "Event Coordinator",
  "Customer Support Representative",
  "Technical Support Specialist",
  "Retail Manager",
  "Store Manager",
  "Hospitality Manager",
  "Chef",
  "Bartender",
  "Environmental Scientist",
  "Research Scientist",
  "Biotechnologist",
  "Agricultural Engineer",
  "Telecom Engineer",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Real Estate Agent",
  "Property Manager",
  "Advertising Specialist",
  "PR Specialist",
  "Web Developer",
  "IT Consultant",
  "Business Analyst",
  "Media Planner",
  "Animator",
  "Video Editor",
  "Sound Engineer",
  "Insurance Agent",
  "Actuary",
  "Surveyor",
  "Urban Planner",
  "Pilot",
  "Flight Attendant",
  "Marine Engineer",
  "Ship Captain",
  "Fitness Trainer",
  "Personal Trainer",
  "Nutritionist",
  "Dietitian",
  "Veterinarian",
  "Zookeeper",
  "Art Director",
  "Interior Designer",
  "Event Planner",
  "Data Analyst",
  "Robotics Engineer",
  "AI Researcher",
  "E-commerce Manager",
  "Game Tester",
  "Scriptwriter",
  "Entrepreneur",
  "Startup Founder",
  "Journalist",
];
export const skills = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "HTML",
  "CSS",
  "SQL",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Kotlin",
  "Swift",
  "Objective-C",
  "PHP",
  "Laravel",
  "Go",
  "Rust",
  "Perl",
  "MATLAB",
  "R",
  "Scala",
  "Haskell",
  "Shell Scripting",
  "Bash",
  "Pandas",
  "NumPy",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Keras",
  "Hadoop",
  "Spark",
  "Kafka",
  "Tableau",
  "Power BI",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Kubernetes",
  "Docker",
  "Terraform",
  "Ansible",
  "Jenkins",
  "Git",
  "GitHub",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "CI/CD",
  "Linux",
  "Windows Server",
  "Ethical Hacking",
  "Penetration Testing",
  "Firewall Management",
  "Cryptography",
  "Blockchain",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Blender",
  "Maya",
  "3D Modeling",
  "Animation",
  "Video Editing",
  "Adobe Premiere Pro",
  "After Effects",
  "Photoshop",
  "Illustrator",
  "Figma",
  "Sketch",
  "InDesign",
  "AutoCAD",
  "SolidWorks",
  "3D Printing",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Visualization",
  "Data Cleaning",
  "Business Intelligence",
  "Digital Marketing",
  "SEO",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Market Research",
  "Customer Relationship Management",
  "E-commerce",
  "Salesforce",
  "SAP",
  "Oracle",
  "Financial Analysis",
  "Accounting",
];

export const locations = [
  "Abu Dhabi, UAE",
  "Amsterdam, Netherlands",
  "Athens, Greece",
  "Auckland, New Zealand",
  "Bangkok, Thailand",
  "Barcelona, Spain",
  "Beijing, China",
  "Berlin, Germany",
  "Bogotá, Colombia",
  "Brisbane, Australia",
  "Brussels, Belgium",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Chicago, USA",
  "Copenhagen, Denmark",
  "Dallas, USA",
  "Delhi, India",
  "Dubai, UAE",
  "Dublin, Ireland",
  "Edinburgh, UK",
  "Frankfurt, Germany",
  "Geneva, Switzerland",
  "Glasgow, UK",
  "Hanoi, Vietnam",
  "Hong Kong, China",
  "Houston, USA",
  "Istanbul, Turkey",
  "Jakarta, Indonesia",
  "Johannesburg, South Africa",
  "Kuala Lumpur, Malaysia",
  "Kyoto, Japan",
  "Las Vegas, USA",
  "Lima, Peru",
  "Lisbon, Portugal",
  "London, UK",
  "Los Angeles, USA",
  "Madrid, Spain",
  "Manila, Philippines",
  "Melbourne, Australia",
  "Mexico City, Mexico",
  "Miami, USA",
  "Milan, Italy",
  "Montreal, Canada",
  "Moscow, Russia",
  "Mumbai, India",
  "Munich, Germany",
  "Nairobi, Kenya",
  "New Delhi, India",
  "New York, USA",
  "Osaka, Japan",
  "Oslo, Norway",
  "Paris, France",
  "Philadelphia, USA",
  "Prague, Czech Republic",
  "Quito, Ecuador",
  "Reykjavik, Iceland",
  "Rio de Janeiro, Brazil",
  "Rome, Italy",
  "San Diego, USA",
  "San Francisco, USA",
  "Santiago, Chile",
  "Sao Paulo, Brazil",
  "Seattle, USA",
  "Seoul, South Korea",
  "Shanghai, China",
  "Singapore, Singapore",
  "Stockholm, Sweden",
  "Sydney, Australia",
  "Taipei, Taiwan",
  "Tokyo, Japan",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Venice, Italy",
  "Vienna, Austria",
  "Warsaw, Poland",
  "Washington D.C., USA",
  "Wellington, New Zealand",
  "Zurich, Switzerland",
];
